nodes:
  - address: 172.31.18.70 # Change this with Private IP of ubuntu (rancher) instance
    internal_address: 172.31.18.70 # Change this with Private IP of ubuntu (rancher) instance
    user: ubuntu
    role: # For the project we have only one node so we give all roles to one node
      - controlplane
      - etcd
      - worker

# ignore_docker_version: true

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

ssh_key_path: ~/.ssh/petclinic-rancher.pem

# Required for external TLS termination with
# ingress-nginx v0.22+
ingress:
  provider: nginx
  options:
    use-forwarded-headers: "true"
